/* 
 * Test API Specification
 *
 * This is a test api for our upcoming project.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nobodyshome@random.games
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing OneOfelementValueValue
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OneOfelementValueValueTests
    {
        // TODO uncomment below to declare an instance variable for OneOfelementValueValue
        //private OneOfelementValueValue instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OneOfelementValueValue
            //instance = new OneOfelementValueValue();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OneOfelementValueValue
        /// </summary>
        [Test]
        public void OneOfelementValueValueInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OneOfelementValueValue
            //Assert.IsInstanceOfType<OneOfelementValueValue> (instance, "variable 'instance' is a OneOfelementValueValue");
        }



    }

}
