/* 
 * Test API Specification
 *
 * This is a test api for our upcoming project.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nobodyshome@random.games
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SessionsUuidBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SessionsUuidBodyTests
    {
        // TODO uncomment below to declare an instance variable for SessionsUuidBody
        //private SessionsUuidBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SessionsUuidBody
            //instance = new SessionsUuidBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SessionsUuidBody
        /// </summary>
        [Test]
        public void SessionsUuidBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SessionsUuidBody
            //Assert.IsInstanceOfType<SessionsUuidBody> (instance, "variable 'instance' is a SessionsUuidBody");
        }


        /// <summary>
        /// Test the property 'SessionInfo'
        /// </summary>
        [Test]
        public void SessionInfoTest()
        {
            // TODO unit test for the property 'SessionInfo'
        }
        /// <summary>
        /// Test the property 'SetPause'
        /// </summary>
        [Test]
        public void SetPauseTest()
        {
            // TODO unit test for the property 'SetPause'
        }

    }

}
