/* 
 * Test API Specification
 *
 * This is a test api for our upcoming project.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nobodyshome@random.games
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UuidUgtBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UuidUgtBodyTests
    {
        // TODO uncomment below to declare an instance variable for UuidUgtBody
        //private UuidUgtBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UuidUgtBody
            //instance = new UuidUgtBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UuidUgtBody
        /// </summary>
        [Test]
        public void UuidUgtBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UuidUgtBody
            //Assert.IsInstanceOfType<UuidUgtBody> (instance, "variable 'instance' is a UuidUgtBody");
        }


        /// <summary>
        /// Test the property 'Ugt'
        /// </summary>
        [Test]
        public void UgtTest()
        {
            // TODO unit test for the property 'Ugt'
        }

    }

}
