/* 
 * Test API Specification
 *
 * This is a test api for our upcoming project.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nobodyshome@random.games
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IUgtApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Retrieve ugts for given user ids.
        /// </summary>
        /// <remarks>
        /// Retrieve all UGTs for a set of supplied user ids.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="developerKey">Developer Api Key</param>
        /// <param name="appKey">App Api Key</param>
        /// <param name="uuids">Uuid List</param>
        /// <returns>Portal</returns>
        Portal DevelopersDeveloperKeyAppKeyUgtGet (string developerKey, string appKey, List<string> uuids);

        /// <summary>
        /// Retrieve ugts for given user ids.
        /// </summary>
        /// <remarks>
        /// Retrieve all UGTs for a set of supplied user ids.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="developerKey">Developer Api Key</param>
        /// <param name="appKey">App Api Key</param>
        /// <param name="uuids">Uuid List</param>
        /// <returns>ApiResponse of Portal</returns>
        ApiResponse<Portal> DevelopersDeveloperKeyAppKeyUgtGetWithHttpInfo (string developerKey, string appKey, List<string> uuids);
        /// <summary>
        /// Fetch UGT for user.
        /// </summary>
        /// <remarks>
        /// Get the UGT set by user for the given developer-app key pair.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid">User Unique Id</param>
        /// <param name="developerKey">Developer Api Key</param>
        /// <param name="appKey">App Api Key</param>
        /// <returns>InlineResponse2001</returns>
        InlineResponse2001 DevelopersDeveloperKeyAppKeyUuidUgtGet (string uuid, string developerKey, string appKey);

        /// <summary>
        /// Fetch UGT for user.
        /// </summary>
        /// <remarks>
        /// Get the UGT set by user for the given developer-app key pair.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid">User Unique Id</param>
        /// <param name="developerKey">Developer Api Key</param>
        /// <param name="appKey">App Api Key</param>
        /// <returns>ApiResponse of InlineResponse2001</returns>
        ApiResponse<InlineResponse2001> DevelopersDeveloperKeyAppKeyUuidUgtGetWithHttpInfo (string uuid, string developerKey, string appKey);
        /// <summary>
        /// Set UGT for user.
        /// </summary>
        /// <remarks>
        /// Set the UGT for given user and the developer-app key pair.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Contains the (valid) ugt to set for the given user/app pair.</param>
        /// <param name="uuid">User Unique Id</param>
        /// <param name="developerKey">Developer Api Key</param>
        /// <param name="appKey">App Api Key</param>
        /// <returns>ModelApiResponse</returns>
        ModelApiResponse DevelopersDeveloperKeyAppKeyUuidUgtPost (UuidUgtBody body, string uuid, string developerKey, string appKey);

        /// <summary>
        /// Set UGT for user.
        /// </summary>
        /// <remarks>
        /// Set the UGT for given user and the developer-app key pair.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Contains the (valid) ugt to set for the given user/app pair.</param>
        /// <param name="uuid">User Unique Id</param>
        /// <param name="developerKey">Developer Api Key</param>
        /// <param name="appKey">App Api Key</param>
        /// <returns>ApiResponse of ModelApiResponse</returns>
        ApiResponse<ModelApiResponse> DevelopersDeveloperKeyAppKeyUuidUgtPostWithHttpInfo (UuidUgtBody body, string uuid, string developerKey, string appKey);
        /// <summary>
        /// Retrieve ugts for user
        /// </summary>
        /// <remarks>
        /// Retrieve a list of ugts for the described user
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid">Unique User Id</param>
        /// <returns>List&lt;User&gt;</returns>
        List<User> UserUuidUgtGet (string uuid);

        /// <summary>
        /// Retrieve ugts for user
        /// </summary>
        /// <remarks>
        /// Retrieve a list of ugts for the described user
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid">Unique User Id</param>
        /// <returns>ApiResponse of List&lt;User&gt;</returns>
        ApiResponse<List<User>> UserUuidUgtGetWithHttpInfo (string uuid);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Retrieve ugts for given user ids.
        /// </summary>
        /// <remarks>
        /// Retrieve all UGTs for a set of supplied user ids.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="developerKey">Developer Api Key</param>
        /// <param name="appKey">App Api Key</param>
        /// <param name="uuids">Uuid List</param>
        /// <returns>Task of Portal</returns>
        System.Threading.Tasks.Task<Portal> DevelopersDeveloperKeyAppKeyUgtGetAsync (string developerKey, string appKey, List<string> uuids);

        /// <summary>
        /// Retrieve ugts for given user ids.
        /// </summary>
        /// <remarks>
        /// Retrieve all UGTs for a set of supplied user ids.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="developerKey">Developer Api Key</param>
        /// <param name="appKey">App Api Key</param>
        /// <param name="uuids">Uuid List</param>
        /// <returns>Task of ApiResponse (Portal)</returns>
        System.Threading.Tasks.Task<ApiResponse<Portal>> DevelopersDeveloperKeyAppKeyUgtGetAsyncWithHttpInfo (string developerKey, string appKey, List<string> uuids);
        /// <summary>
        /// Fetch UGT for user.
        /// </summary>
        /// <remarks>
        /// Get the UGT set by user for the given developer-app key pair.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid">User Unique Id</param>
        /// <param name="developerKey">Developer Api Key</param>
        /// <param name="appKey">App Api Key</param>
        /// <returns>Task of InlineResponse2001</returns>
        System.Threading.Tasks.Task<InlineResponse2001> DevelopersDeveloperKeyAppKeyUuidUgtGetAsync (string uuid, string developerKey, string appKey);

        /// <summary>
        /// Fetch UGT for user.
        /// </summary>
        /// <remarks>
        /// Get the UGT set by user for the given developer-app key pair.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid">User Unique Id</param>
        /// <param name="developerKey">Developer Api Key</param>
        /// <param name="appKey">App Api Key</param>
        /// <returns>Task of ApiResponse (InlineResponse2001)</returns>
        System.Threading.Tasks.Task<ApiResponse<InlineResponse2001>> DevelopersDeveloperKeyAppKeyUuidUgtGetAsyncWithHttpInfo (string uuid, string developerKey, string appKey);
        /// <summary>
        /// Set UGT for user.
        /// </summary>
        /// <remarks>
        /// Set the UGT for given user and the developer-app key pair.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Contains the (valid) ugt to set for the given user/app pair.</param>
        /// <param name="uuid">User Unique Id</param>
        /// <param name="developerKey">Developer Api Key</param>
        /// <param name="appKey">App Api Key</param>
        /// <returns>Task of ModelApiResponse</returns>
        System.Threading.Tasks.Task<ModelApiResponse> DevelopersDeveloperKeyAppKeyUuidUgtPostAsync (UuidUgtBody body, string uuid, string developerKey, string appKey);

        /// <summary>
        /// Set UGT for user.
        /// </summary>
        /// <remarks>
        /// Set the UGT for given user and the developer-app key pair.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Contains the (valid) ugt to set for the given user/app pair.</param>
        /// <param name="uuid">User Unique Id</param>
        /// <param name="developerKey">Developer Api Key</param>
        /// <param name="appKey">App Api Key</param>
        /// <returns>Task of ApiResponse (ModelApiResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<ModelApiResponse>> DevelopersDeveloperKeyAppKeyUuidUgtPostAsyncWithHttpInfo (UuidUgtBody body, string uuid, string developerKey, string appKey);
        /// <summary>
        /// Retrieve ugts for user
        /// </summary>
        /// <remarks>
        /// Retrieve a list of ugts for the described user
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid">Unique User Id</param>
        /// <returns>Task of List&lt;User&gt;</returns>
        System.Threading.Tasks.Task<List<User>> UserUuidUgtGetAsync (string uuid);

        /// <summary>
        /// Retrieve ugts for user
        /// </summary>
        /// <remarks>
        /// Retrieve a list of ugts for the described user
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid">Unique User Id</param>
        /// <returns>Task of ApiResponse (List&lt;User&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<User>>> UserUuidUgtGetAsyncWithHttpInfo (string uuid);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class UgtApi : IUgtApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="UgtApi"/> class.
        /// </summary>
        /// <returns></returns>
        public UgtApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UgtApi"/> class
        /// </summary>
        /// <returns></returns>
        public UgtApi()
        {
            this.Configuration = IO.Swagger.Client.Configuration.Default;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UgtApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public UgtApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Retrieve ugts for given user ids. Retrieve all UGTs for a set of supplied user ids.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="developerKey">Developer Api Key</param>
        /// <param name="appKey">App Api Key</param>
        /// <param name="uuids">Uuid List</param>
        /// <returns>Portal</returns>
        public Portal DevelopersDeveloperKeyAppKeyUgtGet (string developerKey, string appKey, List<string> uuids)
        {
             ApiResponse<Portal> localVarResponse = DevelopersDeveloperKeyAppKeyUgtGetWithHttpInfo(developerKey, appKey, uuids);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieve ugts for given user ids. Retrieve all UGTs for a set of supplied user ids.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="developerKey">Developer Api Key</param>
        /// <param name="appKey">App Api Key</param>
        /// <param name="uuids">Uuid List</param>
        /// <returns>ApiResponse of Portal</returns>
        public ApiResponse< Portal > DevelopersDeveloperKeyAppKeyUgtGetWithHttpInfo (string developerKey, string appKey, List<string> uuids)
        {
            // verify the required parameter 'developerKey' is set
            if (developerKey == null)
                throw new ApiException(400, "Missing required parameter 'developerKey' when calling UgtApi->DevelopersDeveloperKeyAppKeyUgtGet");
            // verify the required parameter 'appKey' is set
            if (appKey == null)
                throw new ApiException(400, "Missing required parameter 'appKey' when calling UgtApi->DevelopersDeveloperKeyAppKeyUgtGet");
            // verify the required parameter 'uuids' is set
            if (uuids == null)
                throw new ApiException(400, "Missing required parameter 'uuids' when calling UgtApi->DevelopersDeveloperKeyAppKeyUgtGet");

            var localVarPath = "/developers/{developerKey}/{appKey}/ugt";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (developerKey != null) localVarPathParams.Add("developerKey", this.Configuration.ApiClient.ParameterToString(developerKey)); // path parameter
            if (appKey != null) localVarPathParams.Add("appKey", this.Configuration.ApiClient.ParameterToString(appKey)); // path parameter
            if (uuids != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "uuids", uuids)); // query parameter
            // authentication (OAuth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DevelopersDeveloperKeyAppKeyUgtGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Portal>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Portal) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Portal)));
        }

        /// <summary>
        /// Retrieve ugts for given user ids. Retrieve all UGTs for a set of supplied user ids.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="developerKey">Developer Api Key</param>
        /// <param name="appKey">App Api Key</param>
        /// <param name="uuids">Uuid List</param>
        /// <returns>Task of Portal</returns>
        public async System.Threading.Tasks.Task<Portal> DevelopersDeveloperKeyAppKeyUgtGetAsync (string developerKey, string appKey, List<string> uuids)
        {
             ApiResponse<Portal> localVarResponse = await DevelopersDeveloperKeyAppKeyUgtGetAsyncWithHttpInfo(developerKey, appKey, uuids);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Retrieve ugts for given user ids. Retrieve all UGTs for a set of supplied user ids.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="developerKey">Developer Api Key</param>
        /// <param name="appKey">App Api Key</param>
        /// <param name="uuids">Uuid List</param>
        /// <returns>Task of ApiResponse (Portal)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Portal>> DevelopersDeveloperKeyAppKeyUgtGetAsyncWithHttpInfo (string developerKey, string appKey, List<string> uuids)
        {
            // verify the required parameter 'developerKey' is set
            if (developerKey == null)
                throw new ApiException(400, "Missing required parameter 'developerKey' when calling UgtApi->DevelopersDeveloperKeyAppKeyUgtGet");
            // verify the required parameter 'appKey' is set
            if (appKey == null)
                throw new ApiException(400, "Missing required parameter 'appKey' when calling UgtApi->DevelopersDeveloperKeyAppKeyUgtGet");
            // verify the required parameter 'uuids' is set
            if (uuids == null)
                throw new ApiException(400, "Missing required parameter 'uuids' when calling UgtApi->DevelopersDeveloperKeyAppKeyUgtGet");

            var localVarPath = "/developers/{developerKey}/{appKey}/ugt";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (developerKey != null) localVarPathParams.Add("developerKey", this.Configuration.ApiClient.ParameterToString(developerKey)); // path parameter
            if (appKey != null) localVarPathParams.Add("appKey", this.Configuration.ApiClient.ParameterToString(appKey)); // path parameter
            if (uuids != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "uuids", uuids)); // query parameter
            // authentication (OAuth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DevelopersDeveloperKeyAppKeyUgtGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Portal>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Portal) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Portal)));
        }

        /// <summary>
        /// Fetch UGT for user. Get the UGT set by user for the given developer-app key pair.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid">User Unique Id</param>
        /// <param name="developerKey">Developer Api Key</param>
        /// <param name="appKey">App Api Key</param>
        /// <returns>InlineResponse2001</returns>
        public InlineResponse2001 DevelopersDeveloperKeyAppKeyUuidUgtGet (string uuid, string developerKey, string appKey)
        {
             ApiResponse<InlineResponse2001> localVarResponse = DevelopersDeveloperKeyAppKeyUuidUgtGetWithHttpInfo(uuid, developerKey, appKey);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Fetch UGT for user. Get the UGT set by user for the given developer-app key pair.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid">User Unique Id</param>
        /// <param name="developerKey">Developer Api Key</param>
        /// <param name="appKey">App Api Key</param>
        /// <returns>ApiResponse of InlineResponse2001</returns>
        public ApiResponse< InlineResponse2001 > DevelopersDeveloperKeyAppKeyUuidUgtGetWithHttpInfo (string uuid, string developerKey, string appKey)
        {
            // verify the required parameter 'uuid' is set
            if (uuid == null)
                throw new ApiException(400, "Missing required parameter 'uuid' when calling UgtApi->DevelopersDeveloperKeyAppKeyUuidUgtGet");
            // verify the required parameter 'developerKey' is set
            if (developerKey == null)
                throw new ApiException(400, "Missing required parameter 'developerKey' when calling UgtApi->DevelopersDeveloperKeyAppKeyUuidUgtGet");
            // verify the required parameter 'appKey' is set
            if (appKey == null)
                throw new ApiException(400, "Missing required parameter 'appKey' when calling UgtApi->DevelopersDeveloperKeyAppKeyUuidUgtGet");

            var localVarPath = "/developers/{developerKey}/{appKey}/{uuid}/ugt";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (uuid != null) localVarPathParams.Add("uuid", this.Configuration.ApiClient.ParameterToString(uuid)); // path parameter
            if (developerKey != null) localVarPathParams.Add("developerKey", this.Configuration.ApiClient.ParameterToString(developerKey)); // path parameter
            if (appKey != null) localVarPathParams.Add("appKey", this.Configuration.ApiClient.ParameterToString(appKey)); // path parameter
            // authentication (OAuth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DevelopersDeveloperKeyAppKeyUuidUgtGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<InlineResponse2001>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (InlineResponse2001) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(InlineResponse2001)));
        }

        /// <summary>
        /// Fetch UGT for user. Get the UGT set by user for the given developer-app key pair.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid">User Unique Id</param>
        /// <param name="developerKey">Developer Api Key</param>
        /// <param name="appKey">App Api Key</param>
        /// <returns>Task of InlineResponse2001</returns>
        public async System.Threading.Tasks.Task<InlineResponse2001> DevelopersDeveloperKeyAppKeyUuidUgtGetAsync (string uuid, string developerKey, string appKey)
        {
             ApiResponse<InlineResponse2001> localVarResponse = await DevelopersDeveloperKeyAppKeyUuidUgtGetAsyncWithHttpInfo(uuid, developerKey, appKey);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Fetch UGT for user. Get the UGT set by user for the given developer-app key pair.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid">User Unique Id</param>
        /// <param name="developerKey">Developer Api Key</param>
        /// <param name="appKey">App Api Key</param>
        /// <returns>Task of ApiResponse (InlineResponse2001)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<InlineResponse2001>> DevelopersDeveloperKeyAppKeyUuidUgtGetAsyncWithHttpInfo (string uuid, string developerKey, string appKey)
        {
            // verify the required parameter 'uuid' is set
            if (uuid == null)
                throw new ApiException(400, "Missing required parameter 'uuid' when calling UgtApi->DevelopersDeveloperKeyAppKeyUuidUgtGet");
            // verify the required parameter 'developerKey' is set
            if (developerKey == null)
                throw new ApiException(400, "Missing required parameter 'developerKey' when calling UgtApi->DevelopersDeveloperKeyAppKeyUuidUgtGet");
            // verify the required parameter 'appKey' is set
            if (appKey == null)
                throw new ApiException(400, "Missing required parameter 'appKey' when calling UgtApi->DevelopersDeveloperKeyAppKeyUuidUgtGet");

            var localVarPath = "/developers/{developerKey}/{appKey}/{uuid}/ugt";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (uuid != null) localVarPathParams.Add("uuid", this.Configuration.ApiClient.ParameterToString(uuid)); // path parameter
            if (developerKey != null) localVarPathParams.Add("developerKey", this.Configuration.ApiClient.ParameterToString(developerKey)); // path parameter
            if (appKey != null) localVarPathParams.Add("appKey", this.Configuration.ApiClient.ParameterToString(appKey)); // path parameter
            // authentication (OAuth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DevelopersDeveloperKeyAppKeyUuidUgtGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<InlineResponse2001>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (InlineResponse2001) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(InlineResponse2001)));
        }

        /// <summary>
        /// Set UGT for user. Set the UGT for given user and the developer-app key pair.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Contains the (valid) ugt to set for the given user/app pair.</param>
        /// <param name="uuid">User Unique Id</param>
        /// <param name="developerKey">Developer Api Key</param>
        /// <param name="appKey">App Api Key</param>
        /// <returns>ModelApiResponse</returns>
        public ModelApiResponse DevelopersDeveloperKeyAppKeyUuidUgtPost (UuidUgtBody body, string uuid, string developerKey, string appKey)
        {
             ApiResponse<ModelApiResponse> localVarResponse = DevelopersDeveloperKeyAppKeyUuidUgtPostWithHttpInfo(body, uuid, developerKey, appKey);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Set UGT for user. Set the UGT for given user and the developer-app key pair.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Contains the (valid) ugt to set for the given user/app pair.</param>
        /// <param name="uuid">User Unique Id</param>
        /// <param name="developerKey">Developer Api Key</param>
        /// <param name="appKey">App Api Key</param>
        /// <returns>ApiResponse of ModelApiResponse</returns>
        public ApiResponse< ModelApiResponse > DevelopersDeveloperKeyAppKeyUuidUgtPostWithHttpInfo (UuidUgtBody body, string uuid, string developerKey, string appKey)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling UgtApi->DevelopersDeveloperKeyAppKeyUuidUgtPost");
            // verify the required parameter 'uuid' is set
            if (uuid == null)
                throw new ApiException(400, "Missing required parameter 'uuid' when calling UgtApi->DevelopersDeveloperKeyAppKeyUuidUgtPost");
            // verify the required parameter 'developerKey' is set
            if (developerKey == null)
                throw new ApiException(400, "Missing required parameter 'developerKey' when calling UgtApi->DevelopersDeveloperKeyAppKeyUuidUgtPost");
            // verify the required parameter 'appKey' is set
            if (appKey == null)
                throw new ApiException(400, "Missing required parameter 'appKey' when calling UgtApi->DevelopersDeveloperKeyAppKeyUuidUgtPost");

            var localVarPath = "/developers/{developerKey}/{appKey}/{uuid}/ugt";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (uuid != null) localVarPathParams.Add("uuid", this.Configuration.ApiClient.ParameterToString(uuid)); // path parameter
            if (developerKey != null) localVarPathParams.Add("developerKey", this.Configuration.ApiClient.ParameterToString(developerKey)); // path parameter
            if (appKey != null) localVarPathParams.Add("appKey", this.Configuration.ApiClient.ParameterToString(appKey)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (OAuth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DevelopersDeveloperKeyAppKeyUuidUgtPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ModelApiResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ModelApiResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ModelApiResponse)));
        }

        /// <summary>
        /// Set UGT for user. Set the UGT for given user and the developer-app key pair.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Contains the (valid) ugt to set for the given user/app pair.</param>
        /// <param name="uuid">User Unique Id</param>
        /// <param name="developerKey">Developer Api Key</param>
        /// <param name="appKey">App Api Key</param>
        /// <returns>Task of ModelApiResponse</returns>
        public async System.Threading.Tasks.Task<ModelApiResponse> DevelopersDeveloperKeyAppKeyUuidUgtPostAsync (UuidUgtBody body, string uuid, string developerKey, string appKey)
        {
             ApiResponse<ModelApiResponse> localVarResponse = await DevelopersDeveloperKeyAppKeyUuidUgtPostAsyncWithHttpInfo(body, uuid, developerKey, appKey);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Set UGT for user. Set the UGT for given user and the developer-app key pair.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Contains the (valid) ugt to set for the given user/app pair.</param>
        /// <param name="uuid">User Unique Id</param>
        /// <param name="developerKey">Developer Api Key</param>
        /// <param name="appKey">App Api Key</param>
        /// <returns>Task of ApiResponse (ModelApiResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ModelApiResponse>> DevelopersDeveloperKeyAppKeyUuidUgtPostAsyncWithHttpInfo (UuidUgtBody body, string uuid, string developerKey, string appKey)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling UgtApi->DevelopersDeveloperKeyAppKeyUuidUgtPost");
            // verify the required parameter 'uuid' is set
            if (uuid == null)
                throw new ApiException(400, "Missing required parameter 'uuid' when calling UgtApi->DevelopersDeveloperKeyAppKeyUuidUgtPost");
            // verify the required parameter 'developerKey' is set
            if (developerKey == null)
                throw new ApiException(400, "Missing required parameter 'developerKey' when calling UgtApi->DevelopersDeveloperKeyAppKeyUuidUgtPost");
            // verify the required parameter 'appKey' is set
            if (appKey == null)
                throw new ApiException(400, "Missing required parameter 'appKey' when calling UgtApi->DevelopersDeveloperKeyAppKeyUuidUgtPost");

            var localVarPath = "/developers/{developerKey}/{appKey}/{uuid}/ugt";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (uuid != null) localVarPathParams.Add("uuid", this.Configuration.ApiClient.ParameterToString(uuid)); // path parameter
            if (developerKey != null) localVarPathParams.Add("developerKey", this.Configuration.ApiClient.ParameterToString(developerKey)); // path parameter
            if (appKey != null) localVarPathParams.Add("appKey", this.Configuration.ApiClient.ParameterToString(appKey)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (OAuth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DevelopersDeveloperKeyAppKeyUuidUgtPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ModelApiResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ModelApiResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ModelApiResponse)));
        }

        /// <summary>
        /// Retrieve ugts for user Retrieve a list of ugts for the described user
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid">Unique User Id</param>
        /// <returns>List&lt;User&gt;</returns>
        public List<User> UserUuidUgtGet (string uuid)
        {
             ApiResponse<List<User>> localVarResponse = UserUuidUgtGetWithHttpInfo(uuid);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieve ugts for user Retrieve a list of ugts for the described user
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid">Unique User Id</param>
        /// <returns>ApiResponse of List&lt;User&gt;</returns>
        public ApiResponse< List<User> > UserUuidUgtGetWithHttpInfo (string uuid)
        {
            // verify the required parameter 'uuid' is set
            if (uuid == null)
                throw new ApiException(400, "Missing required parameter 'uuid' when calling UgtApi->UserUuidUgtGet");

            var localVarPath = "/user/{uuid}/ugt";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (uuid != null) localVarPathParams.Add("uuid", this.Configuration.ApiClient.ParameterToString(uuid)); // path parameter
            // authentication (OAuth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UserUuidUgtGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<User>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<User>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<User>)));
        }

        /// <summary>
        /// Retrieve ugts for user Retrieve a list of ugts for the described user
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid">Unique User Id</param>
        /// <returns>Task of List&lt;User&gt;</returns>
        public async System.Threading.Tasks.Task<List<User>> UserUuidUgtGetAsync (string uuid)
        {
             ApiResponse<List<User>> localVarResponse = await UserUuidUgtGetAsyncWithHttpInfo(uuid);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Retrieve ugts for user Retrieve a list of ugts for the described user
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid">Unique User Id</param>
        /// <returns>Task of ApiResponse (List&lt;User&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<User>>> UserUuidUgtGetAsyncWithHttpInfo (string uuid)
        {
            // verify the required parameter 'uuid' is set
            if (uuid == null)
                throw new ApiException(400, "Missing required parameter 'uuid' when calling UgtApi->UserUuidUgtGet");

            var localVarPath = "/user/{uuid}/ugt";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (uuid != null) localVarPathParams.Add("uuid", this.Configuration.ApiClient.ParameterToString(uuid)); // path parameter
            // authentication (OAuth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UserUuidUgtGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<User>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<User>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<User>)));
        }

    }
}
