/* 
 * Test API Specification
 *
 * This is a test api for our upcoming project.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nobodyshome@random.games
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AvatarApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class AvatarApiTests
    {
        private AvatarApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new AvatarApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AvatarApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' AvatarApi
            //Assert.IsInstanceOfType(typeof(AvatarApi), instance, "instance is a AvatarApi");
        }

        /// <summary>
        /// Test AvatarUidGet
        /// </summary>
        [Test]
        public void AvatarUidGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string uid = null;
            //var response = instance.AvatarUidGet(uid);
            //Assert.IsInstanceOf<Avatar> (response, "response is Avatar");
        }
        /// <summary>
        /// Test UserUuidAvatarsGet
        /// </summary>
        [Test]
        public void UserUuidAvatarsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string uuid = null;
            //var response = instance.UserUuidAvatarsGet(uuid);
            //Assert.IsInstanceOf<List<Avatar>> (response, "response is List<Avatar>");
        }
    }

}
