/* 
 * Test API Specification
 *
 * This is a test api for our upcoming project.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nobodyshome@random.games
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DeveloperApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class DeveloperApiTests
    {
        private DeveloperApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new DeveloperApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DeveloperApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' DeveloperApi
            //Assert.IsInstanceOfType(typeof(DeveloperApi), instance, "instance is a DeveloperApi");
        }

        /// <summary>
        /// Test DevelopersDeveloperKeyAppKeySessionsUuidDelete
        /// </summary>
        [Test]
        public void DevelopersDeveloperKeyAppKeySessionsUuidDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string uuid = null;
            //string developerKey = null;
            //string sessionKey = null;
            //string appKey = null;
            //var response = instance.DevelopersDeveloperKeyAppKeySessionsUuidDelete(uuid, developerKey, sessionKey, appKey);
            //Assert.IsInstanceOf<ModelApiResponse> (response, "response is ModelApiResponse");
        }
        /// <summary>
        /// Test DevelopersDeveloperKeyAppKeySessionsUuidPatch
        /// </summary>
        [Test]
        public void DevelopersDeveloperKeyAppKeySessionsUuidPatchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SessionsUuidBody body = null;
            //string uuid = null;
            //string developerKey = null;
            //string appKey = null;
            //var response = instance.DevelopersDeveloperKeyAppKeySessionsUuidPatch(body, uuid, developerKey, appKey);
            //Assert.IsInstanceOf<ModelApiResponse> (response, "response is ModelApiResponse");
        }
        /// <summary>
        /// Test DevelopersDeveloperKeyAppKeySessionsUuidPost
        /// </summary>
        [Test]
        public void DevelopersDeveloperKeyAppKeySessionsUuidPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string uuid = null;
            //string developerKey = null;
            //string appKey = null;
            //var response = instance.DevelopersDeveloperKeyAppKeySessionsUuidPost(uuid, developerKey, appKey);
            //Assert.IsInstanceOf<InlineResponse200> (response, "response is InlineResponse200");
        }
        /// <summary>
        /// Test DevelopersDeveloperKeyAppKeySessionsUuidPut
        /// </summary>
        [Test]
        public void DevelopersDeveloperKeyAppKeySessionsUuidPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SessionInfo body = null;
            //string uuid = null;
            //string developerKey = null;
            //string appKey = null;
            //var response = instance.DevelopersDeveloperKeyAppKeySessionsUuidPut(body, uuid, developerKey, appKey);
            //Assert.IsInstanceOf<ModelApiResponse> (response, "response is ModelApiResponse");
        }
        /// <summary>
        /// Test DevelopersDeveloperKeyAppKeyUgtGet
        /// </summary>
        [Test]
        public void DevelopersDeveloperKeyAppKeyUgtGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string developerKey = null;
            //string appKey = null;
            //List<string> uuids = null;
            //var response = instance.DevelopersDeveloperKeyAppKeyUgtGet(developerKey, appKey, uuids);
            //Assert.IsInstanceOf<Portal> (response, "response is Portal");
        }
        /// <summary>
        /// Test DevelopersDeveloperKeyAppKeyUuidUgtGet
        /// </summary>
        [Test]
        public void DevelopersDeveloperKeyAppKeyUuidUgtGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string uuid = null;
            //string developerKey = null;
            //string appKey = null;
            //var response = instance.DevelopersDeveloperKeyAppKeyUuidUgtGet(uuid, developerKey, appKey);
            //Assert.IsInstanceOf<InlineResponse2001> (response, "response is InlineResponse2001");
        }
        /// <summary>
        /// Test DevelopersDeveloperKeyAppKeyUuidUgtPost
        /// </summary>
        [Test]
        public void DevelopersDeveloperKeyAppKeyUuidUgtPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UuidUgtBody body = null;
            //string uuid = null;
            //string developerKey = null;
            //string appKey = null;
            //var response = instance.DevelopersDeveloperKeyAppKeyUuidUgtPost(body, uuid, developerKey, appKey);
            //Assert.IsInstanceOf<ModelApiResponse> (response, "response is ModelApiResponse");
        }
    }

}
