/* 
 * Test API Specification
 *
 * This is a test api for our upcoming project.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nobodyshome@random.games
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PortalApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class PortalApiTests
    {
        private PortalApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new PortalApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PortalApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' PortalApi
            //Assert.IsInstanceOfType(typeof(PortalApi), instance, "instance is a PortalApi");
        }

        /// <summary>
        /// Test PortalUidGet
        /// </summary>
        [Test]
        public void PortalUidGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string uid = null;
            //var response = instance.PortalUidGet(uid);
            //Assert.IsInstanceOf<Portal> (response, "response is Portal");
        }
        /// <summary>
        /// Test UserUuidPortalsGet
        /// </summary>
        [Test]
        public void UserUuidPortalsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string uuid = null;
            //var response = instance.UserUuidPortalsGet(uuid);
            //Assert.IsInstanceOf<List<Portal>> (response, "response is List<Portal>");
        }
    }

}
